# Generated by Django 5.1.1 on 2024-09-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koodeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_first_name', models.CharField(max_length=100)),
                ('customer_last_name', models.CharField(default='unknown', max_length=100)),
                ('customer_email', models.EmailField(default='unknown', max_length=254)),
                ('customer_phone_number', models.CharField(max_length=50)),
                ('customer_password', models.CharField(default='unknown', max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('Normal User', 'Normal User'), ('Agent User', 'Agent User')], default='Normal User', max_length=20)),
            ],
        ),
    ]
