# Generated by Django 5.1.1 on 2024-09-30 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koodeapp', '0002_customermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletModel',
            fields=[
                ('wallet_id', models.AutoField(primary_key=True, serialize=False)),
                ('wallet_coins', models.IntegerField(default=300, null=True)),
                ('call_amount', models.FloatField(default=0.0)),
                ('total_minutes', models.IntegerField(default=0)),
                ('total_amount', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koodeapp.customermodel')),
            ],
        ),
    ]
