# Generated by Django 5.1.1 on 2024-10-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koodeapp', '0003_walletmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallPackageModel',
            fields=[
                ('coin_id', models.AutoField(primary_key=True, serialize=False)),
                ('package_price', models.FloatField()),
                ('total_coins', models.IntegerField()),
            ],
        ),
    ]
