# Generated by Django 5.1.1 on 2024-10-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koodeapp', '0008_customermodel_rating_customermodel_terms_conditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
