# Generated by Django 5.1.1 on 2024-10-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koodeapp', '0009_alter_customermodel_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
