# Generated by Django 5.1.1 on 2024-10-09 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koodeapp', '0010_alter_customermodel_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customermodel',
            name='rating',
        ),
        migrations.AddField(
            model_name='customermodel',
            name='adhaar_no',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='languages',
            field=models.CharField(choices=[('Both', 'Both'), ('Malayalam', 'Malayalam'), ('Tamil', 'Tamil')], default='Both', max_length=20),
        ),
        migrations.CreateModel(
            name='RatingModel',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('ratings', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_id', to='koodeapp.customermodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='koodeapp.customermodel')),
            ],
        ),
    ]
