# Generated by Django 5.1.1 on 2024-10-10 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koodeapp', '0011_remove_customermodel_rating_customermodel_adhaar_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='is_existing',
            field=models.BooleanField(default=False),
        ),
    ]
