# Generated by Django 5.1.1 on 2024-10-15 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koodeapp', '0012_customermodel_is_existing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='customer_phone_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='CallDetailsModel',
            fields=[
                ('call_id', models.AutoField(primary_key=True, serialize=False)),
                ('agora_channel_name', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(default=0)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent', to='koodeapp.customermodel')),
                ('caller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caller', to='koodeapp.customermodel')),
            ],
        ),
    ]
