# Generated by Django 5.1.1 on 2024-10-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koodeapp', '0015_alter_customermodel_customer_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log_Register',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255)),
                ('message', models.TextField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='customer_first_name',
            field=models.CharField(default='guest', max_length=100),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='customer_last_name',
            field=models.CharField(max_length=100),
        ),
    ]
