# Generated by Django 5.1.1 on 2024-10-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koodeapp', '0016_log_register_alter_customermodel_customer_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='customer_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
